version: "3.9"

services:
  api:
    build: .
    container_name: tamper-log-api

    ports:
      - "5000:5000"

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - db

    env_file:
      - .env

    command: npm run dev

  db:
    image: postgres:16-alpine

    container_name: tamper-log-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tamperlog

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: